### ISSUE TITLE
[Linux] w3m imgdisplay

### ISSUE THREAD

**Issue by gotbletu** [nogizhopaboroda/cmus-cover-art#1]
could you make this work with w3m imgdisplay; i got it working but it doesnt loop to the next track image without manually killing the w3m browser

IMAGE_VIEWER="w3m -o imgdisplay=/usr/lib/w3m/w3mimgdisplay"

http://i.imgur.com/w6hbgMs.png

**Comment by nogizhopaboroda** [comment]
@gotbletu probably fixed. should refresh on new song now. pull fresh master please.
could you also respond please whether it works or not?

**Comment by gotbletu** [comment]
Thanks sir, works now =)
